[package]
name = "vhdrs"
version = "0.1.0"
edition = "2021"

[dependencies]
windows-sys = { version = "0.59.0", features = [
  "Win32_Foundation",
  "Win32_Security",
  "Win32_Storage",
  "Win32_Storage_Vhd",
  "Win32_System",
  "Win32_System_IO",
] }
anyhow = "1"
